### ISSUE TITLE
Publish arm container

### ISSUE THREAD

**Issue by sdahlbac** [BurntSushi/erd#114]
For people running arm machines, (e.g Mac M1...) it would be helpful if there was an arm version available.

I think it should just be a case of following https://docs.docker.com/build/ci/github-actions/multi-platform/ (but I am not really familiar with the haskell ecosystem, but at least there seems to be a base image available...)

**Comment by FelixVanOost** [comment]
I've been trying to get this working for a while (see my [original comment](https://github.com/BurntSushi/erd/pull/108#issuecomment-1565457755) in May and [active fork](https://github.com/FelixVanOost/erd/tree/build-multiarch-docker-image)) but have been running into consistent issues with GitHub Actions.

Since GitHub doesn't offer native `arm64` runners, the build process relies on emulation via QEMU which can be quite slow. Generally this isn't a big deal, but Haskell seems to download and compile a billion things (I'm also not that familiar with it), causing the runners to either run out of memory or be killed.

The image should build locally without issues, but at the moment I can only think of two ways to get this working here:

- **Provision a native `arm64` runner for this project**. This involves expense that I doubt anyone wants to deal with.
- **Figure out how to set up a GHC cross-compiler for arm64**. I looked into this a while back but the complexity involved is beyond the time I want to commit to this. I'd be happy to support if someone else wants to take it on though.

**Comment by felixvanoost** [comment]
I was finally able to get this working via the use of a 3rd-party integration with [BuildJet](https://buildjet.com/for-github-actions) which provides native `arm64` runners for the build job. This isn't the most elegant solution but the only reasonable one I could come up with. I'll leave it up to @mmzx to decide whether to merge or not.

**Comment by mmzx** [comment]
I've just did:
```
git tag v0.2.2 -f
git push -f --tags
```
This should trigger the gitlab workflow.
